version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: rasav420/ast-canonicalization:latest
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install requirements
          command: pip3 install -r requirements.txt
      - run:
          name: Run Unit tests
          command: ./gradlew test