version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: alyonalyulina/ast-canonicalization:1.0
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Run Unit tests
          command: ./gradlew test