version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:12.0.2-jdk-stretch
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Run Unit tests
          command: ./gradlew test